In [1]:
import numpy as np

In [3]:
a=np.array([1,2,3])
b=np.array([4,5,6])

In [4]:
a

array([1, 2, 3])

In [5]:
b

array([4, 5, 6])

In [7]:
c=np.arange(1,11)
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
c1=np.hstack((a,b))
c1

array([1, 2, 3, 4, 5, 6, 4, 5, 6])

In [10]:
c2=np.arange(2,21,2)
c2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [12]:
c3=np.arange(13,131,13)
c3

array([ 13,  26,  39,  52,  65,  78,  91, 104, 117, 130])

In [14]:
c4=np.linspace(1.0,5.0,num=10)
c4

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [21]:
f=np.array([[1,2,3],[4,5,6]])
f

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
c.size

10

In [18]:
c.shape

(10,)

In [22]:
f.shape

(2, 3)

In [23]:
f[:]

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
f[0:1]

array([[1, 2, 3]])

In [25]:
f[0]#first row

array([1, 2, 3])

In [26]:
f[1] #second row

array([4, 5, 6])

In [27]:
f[1:2]

array([[4, 5, 6]])

In [28]:
f[:,2]

array([3, 6])

In [29]:
f[:,1]

array([2, 5])

In [30]:
f[0:1,2]

array([3])

In [31]:
f[1:2,2]

array([6])

In [32]:
j=np.array([])
j

array([], dtype=float64)

In [33]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
a1=np.random.randint(0,16,size=(4,4))
a1=a1.T
a1

array([[14,  8,  8,  5],
       [ 6,  7,  4,  0],
       [14, 14, 11,  2],
       [ 8,  7,  3,  9]])

In [35]:
j=np.eye(3)
j

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
a1=np.random.randint(0,10,size=(3,2))
a1

array([[9, 5],
       [6, 7],
       [9, 2]])

In [38]:
a2=np.random.randint(0,16,size=(3,4))
a2

array([[ 8, 10,  3,  6],
       [ 2,  5, 14,  0],
       [ 1,  6, 12, 10]])

In [40]:
a=np.array([1,2,3])#brocasting
a+=5
a

array([6, 7, 8])

In [48]:
a=np.random.randint(0,10,size=(3,2))
print(a)
print(a.min())
print(a.max())

[[4 1]
 [5 5]
 [8 6]]
1
8


In [56]:
a=np.random.randint(0,10,size=(3,3))
a

array([[4, 9, 0],
       [6, 1, 3],
       [1, 0, 9]])

In [57]:
a.shape

(3, 3)

In [58]:
a1=a.reshape(9,1)
a1

array([[4],
       [9],
       [0],
       [6],
       [1],
       [3],
       [1],
       [0],
       [9]])

In [59]:
a=np.array([1,2])
b=np.array([3,4])
c=np.concatenate([a+b])
c

array([4, 6])